version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:5.1
        ports:
            - "9090:8080"
        environment:
            # see https://download.geofabrik.de/north-america-latest.osm.pbf for more options
            PBF_URL: https://download.geofabrik.de/north-america-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/north-america/us-updates/
            NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/16/main
        shm_size: 1gb

volumes:
    nominatim-data:
